server:
  port: 8082

spring:
  application:
    name: follow-service
    
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5454/sm_follow
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
      initialization-fail-timeout: 30000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  # Redis Configuration
  data:
    redis:
      host: redis
      port: 6379
      
  # Kafka Configuration
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: follow-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

# JWT Configuration (for validating tokens)
jwt:
  secret: JGJuDvVvbDPgY/Y2zyjogNGtMUQqAaV+W+wY5k9CBf1GJiT4Ll+UtBpxRkZCEIwDX8TRQBO9nAZOVn8ij8fvKQ== # Should match user-service secret

# User Service Configuration
user-service:
  url: http://user-service:8081/api/v1

# Logging
logging:
  level:
    com.microtwitter: DEBUG
    org.springframework.security: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  security:
    enabled: false