services:
  postgres:
    image: postgres:17-alpine
    container_name: sm-auth-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sm_auth
    ports:
      - "5441:5432"
    volumes:
      - auth-postgres-data:/var/lib/postgresql/data

volumes:
  auth-postgres-data: